spring.application.name=order-management-service
server.port=8084

spring.neo4j.uri=bolt://neo4j:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=password

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.influx.url=http://influxdb:8086
spring.influx.token=my-super-secret-auth-token
spring.influx.org=nais_org
spring.influx.bucket=order_bucket

spring.data.redis.host=redis
spring.data.redis.port=6379

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
