apiVersion: 1

datasources:
  - name: Neo4j
    type: kniepdennis-neo4j-datasource
    uid: neo4j
    access: proxy
    url: bolt://neo4j:7687
    jsonData:
      username: neo4j
    secureJsonData:
      password: password

  - name: InfluxDB
    type: influxdb
    uid: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: nais_org
      defaultBucket: restaurant_bucket
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-auth-token

  - name: InfluxDB-Finance
    type: influxdb
    uid: influxdb-finance
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: nais_org
      defaultBucket: finance_bucket
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-auth-token