server:
  port: 8083

spring:
  neo4j:
    uri: bolt://neo4j:7687
    authentication:
      username: neo4j
      password: password
  application:
    name: finance-management-service

  influx:
    url: http://influxdb:8086
    token: my-super-secret-auth-token
    org: nais_org
    bucket: restaurant_bucket

  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 300000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
      healthcheck:
        enabled: true
  instance:
    prefer-ip-address: true